name: Update Asset Data

on:
  schedule:
    - cron: "0 * * * *"  # 매시간 정각
  workflow_dispatch:

permissions:
  contents: write  # 중요! 파이썬의 git push 기능을 허용함

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리를 가져와야 push가 잘 됨

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install yfinance pandas lxml  # requests는 보통 기본설치되지만 필요시 추가

      - name: Run Update Script
        run: python update_data.py
